//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenDBustillo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canchas
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Num_Espectadores { get; set; }
        public int Largo { get; set; }
        public int Ancho { get; set; }
        public int ID_Complejo { get; set; }
    
        public virtual Complejo Complejo { get; set; }
    }
}
