//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenDBustillo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complejo
    {
        public Complejo()
        {
            this.Canchas = new HashSet<Canchas>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
    
        public virtual ICollection<Canchas> Canchas { get; set; }
    }
}
